services:
  kafka1:
    extends:
      file: compose.yaml
      service: kafka1

  kafka2:
    extends:
      file: compose.yaml
      service: kafka2

  kafka3:
    extends:
      file: compose.yaml
      service: kafka3

  kafka-ui:
    extends:
      file: compose.yaml
      service: kafka-ui

  schema-registry:
    extends:
      file: compose.yaml
      service: schema-registry

  connect:
    extends:
      file: compose.yaml
      service: connect

  connect-init:
    extends:
      file: compose.yaml
      service: connect-init

  postgres:
    extends:
      file: compose.yaml
      service: postgres

  order-api:
    image: order-api:latest
    container_name: order-api
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      postgres:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      JAVA_TOOL_OPTIONS: -XX:+UseG1GC -XX:+UseStringDeduplication
      SPRING_PROFILES_ACTIVE: default, container
      INVENTORY_ACCEPTED_ORDERS_TOPIC_NAME: ${INVENTORY_ACCEPTED_ORDERS_TOPIC_NAME}
      INVENTORY_REJECTED_ORDERS_TOPIC_NAME: ${INVENTORY_REJECTED_ORDERS_TOPIC_NAME}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_LOGGING_LEVEL: ${KAFKA_LOGGING_LEVEL}
      KAFKA_MIN_INSYNC_REPLICAS: ${KAFKA_MIN_INSYNC_REPLICAS}
      KAFKA_PARTITIONS: ${KAFKA_PARTITIONS}
      KAFKA_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      ORDERS_BATCH_SIZE: ${ORDERS_BATCH_SIZE}
      ORDERS_MAX_ATTEMPTS: ${ORDERS_MAX_ATTEMPTS}
      ORDERS_PLACED_TOPIC_NAME: ${ORDERS_PLACED_TOPIC_NAME}
      ORDERS_POLL_DELAY: ${ORDERS_POLL_DELAY}
      ORDERS_POLL_INITIAL_DELAY: ${ORDERS_POLL_INITIAL_DELAY}
      ORDERS_PUBLISH_TIMEOUT: ${ORDERS_PUBLISH_TIMEOUT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '8080:80'
    restart: unless-stopped

  inventory-service:
    image: inventory-service:latest
    container_name: inventory-service
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      postgres:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      JAVA_TOOL_OPTIONS: -XX:+UseG1GC -XX:+UseStringDeduplication
      SPRING_PROFILES_ACTIVE: default, container
      INVENTORY_ACCEPTED_ORDERS_TOPIC_NAME: ${INVENTORY_ACCEPTED_ORDERS_TOPIC_NAME}
      INVENTORY_BATCH_SIZE: ${INVENTORY_BATCH_SIZE}
      INVENTORY_POLL_DELAY: ${INVENTORY_POLL_DELAY}
      INVENTORY_POLL_INITIAL_DELAY: ${INVENTORY_POLL_INITIAL_DELAY}
      INVENTORY_REJECTED_ORDERS_TOPIC_NAME: ${INVENTORY_REJECTED_ORDERS_TOPIC_NAME}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_LOGGING_LEVEL: ${KAFKA_LOGGING_LEVEL}
      KAFKA_PARTITIONS: ${KAFKA_PARTITIONS}
      ORDERS_PLACED_TOPIC_NAME: ${ORDERS_PLACED_TOPIC_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '8081:80'
    restart: unless-stopped

  inventory-service-hc:
    extends:
      file: compose.yaml
      service: inventory-service-hc

  tracer:
    extends:
      file: compose.yaml
      service: tracer

  prometheus:
    extends:
      file: compose.yaml
      service: prometheus

  grafana:
    extends:
      file: compose.yaml
      service: grafana
