custom:
  batch_size: 10
  poll_delay: PT1M
  poll_initial_delay: PT1M
  topics:
    accepted: orders.accepted
    placed: orders.placed
    rejected: orders.rejected
logging:
  include-application-name: false
  level:
    com.hamza: info
    org.apache.kafka: warn
    org.hibernate.SQL_SLOW: info
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
server:
  compression:
    additional-mime-types: application/x-ndjson,text/event-stream
    enabled: true
  forward-headers-strategy: native
  port: 8081
  ssl:
    enabled: false
spring:
  application:
    name: inventory-service
  config:
    activate:
      on-profile: default
    import:
      - optional:file:.env[.properties]
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connection-init-sql: set search_path to "${spring.application.name}"
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${custom.pg.host:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
  docker:
    compose:
      enabled: true
      file: compose.dev.yaml
      profiles:
        active:
          - kafka
          - kafka-ui
          - postgres
          - schema-registry
      start:
        arguments:
          - --remove-orphans
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        batch_fetch_style: dynamic
        cache:
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
          use_query_cache: true
          use_second_level_cache: true
        default_batch_fetch_size: 32
        default_schema: ${spring.application.name}
        enable_lazy_load_no_trans: false
        format_sql: false
        generate_statistics: false
        globally_quoted_identifiers: true
        javax:
          cache:
            missing_cache_strategy: fail
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: ehcache.xml
        jdbc:
          batch_size: 32
        jpa:
          compliance:
            query: false
        max_fetch_depth: 1
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: '100'
        show_sql: false
        type:
          json_format_mapper: jackson3
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        schema:
          registry:
            url: http://${custom.registry.host:localhost}:9091
        specific:
          avro:
            reader: true
        spring:
          deserializer:
            value:
              delegate:
                class: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    listener:
      ack-mode: manual
      concurrency: 1
  liquibase:
    analytics-enabled: false
    default-schema: ${spring.application.name}
    enabled: true
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never
  threads:
    virtual:
      enabled: true
  web:
    error:
      include-exception: true
      include-message: always
---
custom:
  batch_size: ${INVENTORY_BATCH_SIZE}
  pg:
    host: postgres
  poll_delay: ${INVENTORY_POLL_DELAY}
  poll_initial_delay: ${INVENTORY_POLL_INITIAL_DELAY}
  registry:
    host: schema-registry
  topics:
    accepted: ${INVENTORY_ACCEPTED_ORDERS_TOPIC_NAME}
    placed: ${ORDERS_PLACED_TOPIC_NAME}
    rejected: ${INVENTORY_REJECTED_ORDERS_TOPIC_NAME}
logging:
  level:
    org.apache.kafka: ${KAFKA_LOGGING_LEVEL:warn}
server:
  port: 80
spring:
  config:
    activate:
      on-profile: container
  docker:
    compose:
      enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      concurrency: ${ORDERS_PARTITIONS}
