@startuml
skinparam sequenceMessageAlign center

control INVENTORY_SERVICE as SERVICE
database DATABASE as DB
queue KAFKA as K

loop
    SERVICE --> K: listen
    K --> SERVICE: consume events
    SERVICE --> DB: check idempotency
    note right: **only processed once**
    alt never processed before
        group transactional
            SERVICE --> DB: save event as processed
            SERVICE --> SERVICE: process order
            note right: for demo: randomly accept or reject order\n(accepted/rejected topics)
            SERVICE --> SERVICE: create outbox
            SERVICE --> DB: save outbox
        end
        SERVICE --> K: ACK
        note right: commit offset\nif it fails idempotency check will ignore it
    else already processed
        SERVICE --> SERVICE: skip
    end
end

group listener on `outbox_insert_channel`
    SERVICE <--> DB
    note across: same flow as ORDER_API
end

group low freq rescue periodic poll
      SERVICE --> DB
      note across: same flow as ORDER_API
end
@enduml
