@startuml
skinparam sequenceMessageAlign center

actor USER as U
boundary ORDER_API as API
database DATABASE as DB
queue KAFKA

U -> API : POST order
group transactional
    API --> DB : save order
    DB --> API : order
    API --> API : create event
    API --> API : create outbox
    API --> DB : save outbox
end
API -> U : order

DB --> API: notify
note right: trigger on insert that notify **`outbox_insert_channel`**

group listener on `outbox_insert_channel`
    loop until no unpublished outbox is retrieved
        API --> DB : get unpublished outbox batch
        note right: **publishedAt == null AND attempts < max_attempts**\nwill lock current batch in DB in case of concurrency\nconcurrent will pick next batch
        DB --> API : outbox batch
        API --> API : extract events
        API --> KAFKA : publish events batch
        alt successful publish
            KAFKA -[#green]-> API : ACK publish
            API --> DB : flag outbox as published
            note right: set publishedAt
        else error publish
            KAFKA -[#red]-> API : ERROR
            API -[#red]-> API : or ERROR
            alt recoverable error
                API --> API : do nothing
                note right
                    **recoverable/transient errors:**
                    timeout
                    election in progress
                    broker down
                    ...etc
                end note
            else non recoverable error
                alt attempts < max_attempts
                    API --> DB : inc attempts
                    note right
                        **non recoverable/permanent errors:**
                        payload
                        serialization
                        ...etc
                    end note
                else attempts >= max_attempts
                    API --> DB : flag outbox as dead letter
                    note right: set lastError
                end
            end
        end
    end
end

group low freq rescue periodic poll
      API --> DB
      note right: previous outbox publication flow\nin case listener/notify fails
end
@enduml
