@startuml
actor USER as U
boundary ORDER_API as API
database DATABASE as DB
queue KAFKA as K

group REST
    U -> API: POST /api/order
    group transactional
        API -> DB: save order
        note right: status pending
        DB --> API: order
        API -> API: create order placed event
        API -> API: create outbox
        API -> DB: save outbox
    end
    API --> U: 201 location /api/order/{id}
end

group listener on DB `outbox_channel`
    API <-> DB: listen/notify
    note left: manual CDC\n1 thread separate from hikari pool
    note right: trigger on **outbox.insert** that notify **outbox_channel**
    API -> API: trigger drain service
    loop until no unpublished outbox is retrieved
        note across: keep draining unpublished outbox messages until none is left then sleeps\nis gated by a linear back off in case kafka env is unhealthy
        group transactional
            note across: transaction here to lock current batch in DB in case of concurrency\nany concurrent will pick next batch
            API -> DB: get unpublished outbox batch
            note right: **publishedAt == null AND attempts < max_attempts**
            DB --> API: outbox batch
            API -> API: extract events
            API -> K: publish batch
            note right: orders.placed topic
            K --> API: return futures
            loop for each future
                API -> API: acquire future result
                alt successful publish
                    K -[#green]-> API: ACK publish
                    API -> DB: flag outbox as published
                    note right: set publishedAt
                else unsuccessful publish
                    K -[#red]-> API: ERROR
                    API -[#red]-> API: or ERROR
                    alt recoverable error
                        note across
                            **recoverable/transient errors:**
                            timeout
                            election in progress
                            broker down
                            schema registry unreachable
                        end note
                        API -> API: do nothing
                    else non recoverable error
                        note across
                            **non recoverable/permanent errors:**
                            bad payload
                            serialization
                            incompatible schema
                            unhandled
                        end note
                        alt attempts < max_attempts
                            API -> DB: inc attempts
                        else attempts >= max_attempts
                            API -> DB: flag outbox as dead letter
                            note right: set lastError
                        end
                    end
                end
            end
        end
    end
end

group low freq rescue periodic poll
    note across: rescue in case listener fails or back off kicks in
    API -> API: trigger drain service
end

group consumers
    loop
        note across: N concurrent listener: 1 per partition
        API -> K: listen
        note right: orders.[accepted|rejected] topics
        K --> API: new event
        group transactional
            note across: idempotency check: only consumed once
            API -> DB: dedup by eventId
            DB --> API: response
            alt never consumed before
                API -> API: create inbox
                API -> DB: save inbox
                note right: dedup table
                API -> DB: update order status
                note right: topic determine status
                API -> K: ACK
                note right: commit read offset\nif it fails idempotency check will ignore it
            else already consumed
                API -> K: ACK
                note right: commit read offset\nif it fails idempotency check will ignore it
            end
        end
    end
end

group REST
    U -> API: GET /api/order/{id}
    API -> DB
    DB -> API
    API --> U: order
end
@enduml
